<%@ page import="java.sql.*,product.DBConnection"%>

<%
    int nextProductId = 1;

    try {
        Connection con = DBConnection.getCon();
        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(
            "SELECT COALESCE(MAX(id),0)+1 AS next_id FROM products"
        );

        if (rs.next()) {
            nextProductId = rs.getInt("next_id");
        }

        rs.close();
        st.close();
        con.close();

    } catch (Exception e) {
        nextProductId = 1;
    }
%>

<html>
<head>
    <title>Add Product</title>

    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial;
            background-color: #f4f6f9;
        }

        .container {
            width: 50%;
            margin: 50px auto;
            background: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 25px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 8px;
        }

        input, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }

        input[readonly] {
            background: #f1f1f1;
            font-weight: bold;
            text-align: center;
        }

        .btn-submit {
            width: 100%;
            padding: 12px;
            background: #3f51b5;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .btn-back {
            display: inline-block;
            margin-top: 15px;
            padding: 10px 20px;
            background: #666;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }

        .note {
            font-size: 12px;
            color: #777;
            text-align: center;
            margin-top: 5px;
        }
    </style>
</head>

<body>

<div class="container">

<h1>Add New Product</h1>

<form action="AddProductServlet" method="post">

    <!-- DISPLAY ONLY -->
    <div class="form-group">
        <label>Product ID (Next Expected):</label>
        <input type="text" value="<%=nextProductId%>" readonly>
        <div class="note">This is only a preview. Final ID is generated by database.</div>
    </div>

    <div class="form-group">
        <label>Product Name:</label>
        <input type="text" name="name" required>
    </div>

    <div class="form-group">
        <label>Category:</label>
        <select name="category" required>
            <option value="">Select Category</option>
            <option>Electronics</option>
            <option>Clothing</option>
            <option>Books</option>
            <option>Groceries</option>
            <option>Furniture</option>
            <option>Sports</option>
            <option>Other</option>
        </select>
    </div>

    <div class="form-group">
        <label>Price:</label>
        <input type="number" name="price" step="0.01" required>
    </div>

    <div class="form-group">
        <label>Quantity:</label>
        <input type="number" name="quantity" required>
    </div>

    <button type="submit" class="btn-submit">Add Product</button>

</form>

<a href="dashboard.jsp" class="btn-back">Back to Dashboard</a>

</div>

</body>
</html>